import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <Providers>
        <body className={inter.className}>
          <div className="h-screen bg-[#131314]">
          {/* <img src="https://nextui.pro/images/default-gradient.png" alt="" className="absolute h-screen w-screen mt-[-20vh]"/> */}
          {children}
            </div>
        </body>
        </Providers>
        </ClerkProvider>
    </html>
  );
}
